# Set version numbers

set(PROJECT_VERSION 0.0.5)

set(SCION_CPP_VERSION_MAJOR 0)
set(SCION_CPP_VERSION_MINOR 0)
set(SCION_CPP_VERSION_PATCH 5)
set(SCION_CPP_VERSION ${SCION_CPP_VERSION_MAJOR}.${SCION_CPP_VERSION_MINOR}.${SCION_CPP_VERSION_PATCH})
set(SCION_CPP_SO_VERSION ${SCION_CPP_VERSION_MAJOR})

set(SCION_C_VERSION 0.0.5)
set(SCION_C_SO_VERSION 0)

set(INTERPOSER_VERSION 0.0.5)
set(INTERPOSER_SO_VERSION 0)

set(SCITRA_TUN_VERSION 0.1.0)

set(SCION2IP_VERSION 0.1.0)
