# Set version numbers

set(PROJECT_VERSION 0.0.3)

set(SCION_CPP_VERSION 0.0.3)
set(SCION_CPP_SO_VERSION 0)

set(SCION_C_VERSION 0.0.3)
set(SCION_C_SO_VERSION 0)

set(INTERPOSER_VERSION 0.0.3)
set(INTERPOSER_SO_VERSION 0)

set(SCITRA_TUN_VERSION 0.0.3)

set(SCION2IP_VERSION 0.0.3)
